In [93]:
import numpy as np

In [94]:
"""

Mantik:
    QR ile matris T = Q*R iki matris olarak yazilir. Sonra T matrisi T = R*Q yapilir.
    Bu yeterli yapilirsa matrisin asal kösegeni eigenvalue'lara yakınsar.

Parametreler:
    T - array: Karesel matris
    num_i - int: iterasyon
    e_s - float: Erken durma için tolerans

"""
def mini_qr(T, num_i=50000, e_s=1e-9):
    # Orijinal matrisi bozmuyoruz
    Tk = np.array(T, dtype=float)

    for i in range(num_i):
        # A = Q * R -> Bunun formulu gram-schmidt ortanormallestirmesi kullanir basitce ortanormal tabani ardindan sutun vektorlerini kullaniriz
        # R satirla ortanormal tabanin sutunlarla ic carpimini barindiran ust ucgenseldir. Q ise direkt bu ortanormal taban vektorlerinin sutun olarak matris olusturmus halidir.
        Q, R = np.linalg.qr(Tk)

        # T = R * Q
        Tk_new = np.dot(R, Q)

        # Erken durdurma
        off_diagonal_sum = np.sum(np.abs(Tk_new - np.diag(np.diag(Tk_new))))
        if off_diagonal_sum < e_s:
            print(f"Erken Durduruluyor!")
            return np.diag(Tk_new)

        Tk = Tk_new

    print("Maksimum iterasyon!")
    return np.diag(Tk)

In [95]:
# Test matris olusturalim
# Simetrik matrisler QR algoritması icin ideal.
M = np.array([[10,  2,  3,  1],
              [ 2,  8,  5,  2],
              [ 3,  5, 12,  4],
              [ 1,  2,  4,  7]])

print("1. MATRIX:")
print(M)

1. MATRIX:
[[10  2  3  1]
 [ 2  8  5  2]
 [ 3  5 12  4]
 [ 1  2  4  7]]


In [96]:
custom_eigenvalues = mini_qr(M, 100000)
custom_eigenvalues_sorted = np.sort(custom_eigenvalues) # en kucuk ikisinde de basa gelsin

print(f"2. mini_qr: {custom_eigenvalues_sorted}")

Erken Durduruluyor!
2. mini_qr: [ 4.24806175  5.38224081  8.51593751 18.85375993]


In [97]:
numpy_eigenvalues, numpy_eigenvectors = np.linalg.eig(M)
numpy_eigenvalues_sorted = np.sort(numpy_eigenvalues)

print(f"3. linalg.eig: {numpy_eigenvalues_sorted}")

3. linalg.eig: [ 4.24806175  5.38224081  8.51593751 18.85375993]


In [98]:
tolerans = 1e-6
is_close = np.where(np.abs(custom_eigenvalues_sorted - numpy_eigenvalues_sorted) <= tolerans, True, False).all() # Acik yazdim da where gereksiz aslinda

if is_close:
    print(f"Sonuclar ({tolerans} toleransla) Benzer!")
else:
    print("Sonuclar Kotu!")

Sonuclar (1e-06 toleransla) Benzer!
